baseURL = ""
title = "Bigspring Hugo"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
paginate = "3"
summaryLength = "15"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
publishDir = "public"

[markup.goldmark.renderer]
unsafe = true

[params]
logo = "images/logo.png"
logo_width = "200px"
description = "This is meta description"
author = "Themefisher"
contact_form_action = "#"
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

  [params.preloader]
  enable = false
  preloader = ""

  [params.navigation_button]
  enable = true
  label = "Get Started"
  link = "contact"

  [[params.social]]
  title = "facebook"
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  title = "twitter"
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  title = "skype"
  icon = "ti-skype"
  link = "#"

  [[params.social]]
  title = "linkedin"
  icon = "ti-linkedin"
  link = "#"

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 1

[[menu.main]]
name = "Pricing"
URL = "pricing"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 4

[[menu.footer_left]]
name = "About Us"
URL = "#"

[[menu.footer_left]]
name = "Quick Start"
URL = "#"

[[menu.footer_left]]
name = "Pricing"
URL = "pricing"

[[menu.footer_middle]]
name = "Pricing"
URL = "pricing"

[[menu.footer_middle]]
name = "Platform"
URL = "#"

[[menu.footer_middle]]
name = "Features"
URL = "#"

[[menu.footer_right]]
name = "Privacy Policy"
URL = "privacy-policy"

[[menu.footer_right]]
name = "Terms & Conditions"
URL = "terms-conditions"

[[menu.footer_right]]
name = "FAQ"
URL = "faq"
